[project]
name = "greedyboi"
version = "0.1.0"
description = "An implementation and solver of the dice game Greed"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.3",
    "scipy>=1.16.2",
]
